var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,e={next:function(){if(c<a.length){var d=c++;return{value:b(d,a[d]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill=function(a,b,c,e){if(b){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in c||(c[d]={});c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof d?a:new d(function(b,f){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){e(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var d=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(g){b.reject(g)}};d.prototype.createResolveAndReject_=
function(){function a(a){return function(f){c||(c=!0,a.call(b,f))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};d.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof d)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};d.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(g){this.reject_(g);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};d.prototype.reject_=function(a){this.settle_(2,a)};d.prototype.fulfill_=function(a){this.settle_(1,a)};d.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var l=new b;d.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};d.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(k){c.reject(k)}};d.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(n){f(n)}}:b}var e,f,m=new d(function(a,
b){e=a;f=b});this.callWhenSettled_(c(a,e),c(b,f));return m};d.prototype.catch=function(a){return this.then(void 0,a)};d.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?l.asyncExecute(c):this.onSettledCallbacks_.push(function(){l.asyncExecute(c)})};d.resolve=c;d.reject=function(a){return new d(function(b,c){c(a)})};d.race=function(a){return new d(function(b,
d){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())c(f.value).callWhenSettled_(b,d)})};d.all=function(a){var b=$jscomp.makeIterator(a),e=b.next();return e.done?c([]):new d(function(a,d){function f(b){return function(c){h[b]=c;g--;0==g&&a(h)}}var h=[],g=0;do h.push(void 0),g++,c(e.value).callWhenSettled_(f(h.length-1),d),e=b.next();while(!e.done)})};return d},"es6-impl","es3");
var scripts=document.getElementsByTagName("script"),index=scripts.length-1,myScript=scripts[index],params=parseQuery(myScript.src.replace(/^[^\?]+\??/,"")),Debug="debug"in params||!1;function parseQuery(a){var b={};a=("?"===a[0]?a.substr(1):a).split("&");for(var c=0;c<a.length;c++){var e=a[c].split("=");b[decodeURIComponent(e[0])]=decodeURIComponent(e[1]||"")}return b}
function toQueryString(a){return Object.keys(a).map(function(b){return encodeURIComponent(b)+"="+encodeURIComponent(a[b])}).join("&")}function debug(a,b,c){if(Debug)return c?console.error(a,b):console.log(a,b)}
var RodinSocket=function(a,b){this.emitBuffer={};this.listenerBuffer={};RodinSocket.disconnected=RodinSocket.disconnected.bind(this);this.onMessage=this.onMessage.bind(this);this.broadcastToAll=this.broadcastToAll.bind(this);this.subscribeToEvents=this.subscribeToEvents.bind(this);this.getConnectedUsersList=this.getConnectedUsersList.bind(this);this.sendMessageToUser=this.sendMessageToUser.bind(this);this.joinRoom=this.joinRoom.bind(this);this.leaveRoom=this.leaveRoom.bind(this);this.getRooms=this.getRooms.bind(this);
this.deleteRoom=this.deleteRoom.bind(this);this.broadcastToRoom=this.broadcastToRoom.bind(this);this.subscribe=this.subscribe.bind(this);this.connect=this.connect.bind(this);this.reconnect=this.reconnect.bind(this);this.disconnect=this.disconnect.bind(this);this.onConnected=this.onConnected.bind(this);this.setData=this.setData.bind(this);this.mySocketId=this.mySocketId.bind(this);this.isMe=this.isMe.bind(this);this.validateSocketConnection=this.validateSocketConnection.bind(this)};
RodinSocket.prototype.connect=function(a){var b=this;a=toQueryString(a);this.subscribe().then(function(c){console.log("response",c.data);b.ns=c.data.ns;b.host=params.host;debug("NS SETTINGS",[b.ns,params,b.host]);b.Socket=io(b.host+"/"+b.ns,{query:a,resource:"socket.io"});return b.subscribeToEvents()}).catch(function(a){console.log(a);b.emitBuffer={};b.listenerBuffer={}})};RodinSocket.prototype.disconnect=function(){this.Socket.disconnect()};RodinSocket.prototype.mySocketId=function(){return this.Socket.id};
RodinSocket.prototype.isMe=function(a){return a.socketId==this.Socket.id?!0:!1};RodinSocket.prototype.subscribeToEvents=function(){var a=this;this.Socket.on("connect",function(b){return a.connected(b)});this.Socket.on("subscribeToApp",this.subscribe);this.Socket.on("disconnect",RodinSocket.disconnected);this.Socket.on("onError",RodinSocket.onError)};RodinSocket.prototype.reconnect=function(){this.Socket.connect()};
RodinSocket.prototype.connected=function(a){if(0<Object.keys(this.listenerBuffer).length){for(var b in this.listenerBuffer)if("connection"==b)this.listenerBuffer[b](this.Socket.connected);else this.Socket.on(b,this.listenerBuffer[b]);this.listenerBuffer={}}if(0<Object.keys(this.emitBuffer).length){for(var c in this.emitBuffer)this.Socket.emit(c,this.emitBuffer[c]);this.emitBuffer={}}debug("connected",a)};
RodinSocket.prototype.onConnected=function(a){if(!this.Socket)return this.listenerBuffer.connection=a;a(this.Socket.connected)};RodinSocket.disconnected=function(a){debug("disconnected",a)};RodinSocket.prototype.onMessage=function(a,b){if(!this.Socket)return this.listenerBuffer[a]=b;this.Socket.on(a,b)};RodinSocket.onError=function(a){debug("Socket Request error",a,!0)};
RodinSocket.prototype.broadcastToAll=function(a,b){a={event:a,data:b};this.validateSocketConnection("broadcastToAll",a)&&this.Socket.emit("broadcastToAll",a)};RodinSocket.prototype.broadcastToRoom=function(a,b,c){a={roomName:c,eventName:a||!1,data:b};this.validateSocketConnection("broadcastToRoom",a)&&this.Socket.emit("broadcastToRoom",a)};
RodinSocket.prototype.sendMessageToUser=function(a,b){a={event:"sendMessageToUser",socketIds:a,message:b};this.validateSocketConnection("message",a)&&this.Socket.emit("message",a)};RodinSocket.prototype.setData=function(a){this.validateSocketConnection("setData",a)&&this.Socket.emit("setData",a)};RodinSocket.prototype.getConnectedUsersList=function(){this.validateSocketConnection("getConnectedUsersList",{})&&this.Socket.emit("getConnectedUsersList",{})};
RodinSocket.prototype.joinRoom=function(a,b){a={roomName:a,notifyAll:b};this.validateSocketConnection("joinRoom",a)&&this.Socket.emit("joinRoom",a)};RodinSocket.prototype.leaveRoom=function(a,b){a={roomName:a,notifyAll:b};this.validateSocketConnection("leaveRoom",a)&&this.Socket.emit("leaveRoom",a)};RodinSocket.prototype.getRooms=function(){this.validateSocketConnection("getRooms",{})&&this.Socket.emit("getRooms",{})};
RodinSocket.prototype.deleteRoom=function(a){a={roomName:a};this.validateSocketConnection("deleteRoom",a)&&this.Socket.emit("deleteRoom",a)};
RodinSocket.prototype.subscribe=function(){var a=params.host+"/socket-server/subscribe";return new Promise(function(b,c){var e=new XMLHttpRequest;e.open("POST",a);e.setRequestHeader("Content-Type","application/json;charset=UTF-8");e.onload=function(){return 200===e.status?b(JSON.parse(e.response)):c(Error(e.statusText))};e.onerror=function(a){return c(Error("Network Error: "+a))};e.send(JSON.stringify(params))})};
RodinSocket.prototype.validateSocketConnection=function(a,b){return this.Socket?!0:(this.emitBuffer[a]=b,!1)};debug("PARAMS",params);
