(function(){app.controller("MainCtrl",function(e,a,A,B,f,h,v,C,D,l,g,q,w,r,k,E,F,d,G,H,m,I,x,y){function z(){function t(c){c&&(a.socketSubscribeToken=c);if(a.socketSubscribeToken){l(function(){r.get(q,function(b){a.allNotifications=b.notifications.filter(function(a){return!!a});a.notifications=[];a.notificationBadge=b.notificationBadge;a.notificationsFrom=0;a.notificationTo=10})},500);var b=!1;a.loadMoreNotifications=function(){if(!b&&a.allNotifications.length!=a.notifications.length){b=!0;var c=
a.allNotifications.slice(a.notificationsFrom,a.notificationTo);a.notifications=a.notifications.concat(c);a.notificationsFrom+=10;a.notificationTo+=10;b=!1}}}}function u(c){_.each(c,function(b){switch(b.type){case 1:a.updateNotification(b.notificationUpdate.notifications);break;case 2:case 3:case 4:case 14:d(w.reloadDriversData(b.driver,function(c){a.$broadcast("updateDriver",{item:b.driver,type:b.type});e.$broadcast("updateOrderDetialsDriver",b.driver)}),500);d(e.$broadcast("updateDriverInTeam",{}),
500);break;case 5:d(a.$broadcast("updateAll",b));break;case 6:d(e.$broadcast("orderDetailsUpdate",b),500);d(e.$broadcast("orderUpdated",b.schedule),300);6==b.schedule.type&&d(a.$broadcast("ganttUpdate",{item:b.schedule,type:"edit"}),300);break;case 7:d(a.$broadcast("ganttUpdate",{item:b.deletedId,type:"delete"}),300);break;case 8:case 9:case 10:case 11:case 16:case 17:d(a.$broadcast("updatePredefineFilter",b),300);break;case 15:case 13:d(a.$broadcast("updateAll",b));break;case 18:d(e.$broadcast("pushToSchedule",
b));break;case 12:d(a.$broadcast("freeCapUpdate",{message:"capUpdate"}),300);break;case 19:d(e.$broadcast("orderDetailsUpdate",b),500);d(e.$broadcast("orderUpdated",b.order),300);break;case 21:d(a.$broadcast("updateDriverOrders",b),300),d(e.$broadcast("newData",{}),500)}});a.socketBuffer=[]}function n(){a.rating=[];a.socketSubscribeToken&&(k.scope||(k.scope=a),k.init(function(){k.subscribe("/topic/socketUpdates/"+a.socketSubscribeToken+"",function(c){c=JSON.parse(c.body);console.log("sock.:",c);var b=
_.filter(c,function(a){return 20==a.type});0<b.length&&(b=_.map(b,function(a){return a.deletedId}),e.$broadcast("removeOrders",b));if(a.blockSocketPushes)return a.socketBuffer=a.socketBuffer.concat(c);u(c)})}))}a.$on("createOrderOpen",function(c,b){a.blockSocketPushes=b;console.log(a.socketBuffer);!b&&0<a.socketBuffer.length&&u(a.socketBuffer)});a.mainCtrlInited=!0;a.logOut=function(){a.contentLoaded=!1;f.remove("jwt");f.remove("socketToken");f.remove("role");m.deleteCookie("jwt","/",h.host());m.deleteCookie("socketToken",
"/",h.host());m.deleteCookie("role","/",h.host());g.ga&&g.ga("send","event","app","logOut","logOut");a.socketSubscribeToken=void 0;switch(Configs.CUR_ENV){case "STAGE":var c="http://site.stage.fr8.guru/";break;case "DEV":c="http://fr8.dev/";break;case "PROD":c="http://www.fr8.guru/";break;case "STABLE":c="https://stable.fr8.guru/"}window.location.href=c};a.loadDetalisEvent=function(c){a.loadDetailsMovementId=c;a.createOrderModalInstance=x.open({animation:!0,templateUrl:"./modules/global/orderDetails/index.html",
controller:"OrderDetailsCtrl",controllerAs:"vm",windowClass:"event-details",size:"lg",resolve:{movementId:function(){return a.loadDetailsMovementId},orderDetails:!1,shareToken:!1}});a.createOrderModalInstance.result.then(function(b){a.selected=b},function(){$(".modal-backdrop").remove()})};a.redirectToFindLoads=function(a,b){var c=b.endWindowEnd>1E3*moment().unix();!$(a.target).hasClass("equipments")&&c&&(a={startAddress:b.startAddress,endAddress:b.endAddress,maxStartDeadhead:150,maxEndDeadhead:b.endAddress?
150:!1,startDate:b.from<moment(new Date)?moment(new Date).toDate():b.from.toDate(),endDate:b.to.toDate(),startUnix:b.from<moment(new Date)?1E3*moment(new Date).unix():b.unixStart,endUnix:b.unixEnd,equipment:b.equipments,forceClick:!0},y.collectedData=a,h.path("findloads"))};var p=!1;a.confirmNotification=function(c,b,d){p||(p=!0,b&&(a.rating[c.serverId]=b),r.confirm(c,b,a.notifications,a.allNotifications,function(b){a.notifications=b.notifications;a.allNotifications=b.allNotifications;3>=a.notifications.length&&
0<a.allNotifications.length&&(a.notificationsFrom=0,a.notificationTo=10,a.loadMoreNotifications());a.rating=[];p=!1}))};a.updateNotification=function(c){c=q.notificationsMapper(c);_.each(c,function(b,c){a.allNotifications.unshift(b);a.notifications.unshift(b)});a.notificationBadge=a.notifications.length;l(function(){a.$$phase||a.$apply()})};a.socketSubscribeToken=f.get("socketToken");a.$on("reconnectSocket",function(a,b){n()});a.$watch("firstLogIn",function(a){a&&n()});a.$on("openOrderDetails",function(c,
b){a.loadDetalisEvent(b.movementId)});a.$on("socketToken",function(a,b){t(b.socketToken)});t();n()}a.$route=v;a.modalActivate=!1;a.mapLoaded=!1;a.clientOs=g.jscd.os;a.clientBrowser=g.jscd.browser?g.jscd.browser.toLowerCase():"unknown";a.isIE=detectIE()?"ie _"+detectIE():"";a.contentLoaded=!1;a.notificationBadge=0;e.firstLogIn=!1;a.alerts=[];a.socketBuffer=[];a.orderDetailsForm={shipperInfo:{},consigneeInfo:{},brokerInfo:{}};a.env=Configs.CUR_ENV.toLowerCase();a.isFleet="FLEET"==f.get("role")?!0:!1;
l(function(){a.ctrl=a.$route.current.$$route.controller.toLowerCase()},1E3);a.contentLoaded=!1;a.modalIsOpen=!1;a.weekStart=moment().subtract(1,"days").startOf("day");a.weekEnd=moment().add(2,"days").endOf("day");a.consigneeEditMode=!1;a.noteEditMode=!1;a.refIdEditMode=!1;a.shipperEditMode=!1;e.endorsements=[{id:1,name:"T"},{id:2,name:"N"},{id:3,name:"H"},{id:4,name:"MIL"},{id:5,name:"TEAM"}];a.$watch("contentLoaded",function(){!a.contentLoaded||a.sharedCtrl||a.mainCtrlInited||z()});a.$watch("alerts",
function(d,e){_.each(a.alerts,function(d,e){d.timeout||(a.alerts[e].timeout=setTimeout(function(){a.$apply(function(){a.alerts.shift()})},Configs.CLEAR_ALERTS))})},!0);a.$on("alertMessage",function(d,e){a.alerts.push({type:e.type,message:e.message})});a.closeAlert=function(d){a.alerts.splice(d,1)}});String.prototype.capitalize=function(){return this.replace(/(?:^|\s)\S/g,function(e){return e.toUpperCase()})}})();
